export const MAX_VISITS_PER_DAY = 1

export const VISIT_CODES = {
  OK: "OK",
  ALREADY_SCANNED_TODAY: "ALREADY_SCANNED_TODAY",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  NO_ACTIVE_PROMOTION: "NO_ACTIVE_PROMOTION",
} as const

export const REDEEM_CODES = {
  OK: "OK",
  NO_PENDING_REWARD: "NO_PENDING_REWARD",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
} as const
